### ISSUE TITLE
Unable to compile in the relocalization branch

### ISSUE THREAD

**Issue by mini-1235** [fetty31/fast_LIMO#17]
Hi, I noticed that the commit 4205a51cbe0572daa77e6f69955985701ab960ff is actually causing a regression:
```cpp
 113 |             KD_TREE<MapPoint>::Ptr new_map = KD_TREE<MapPoint>::Ptr (new KD_TREE<MapPoint>(0.3, 0.6, 0.01));
      |             ^~~~~~~
/home/src/fast_LIMO/include/fast_limo/Modules/Mapper.cpp:113:29: error: expected primary-expression before ‘>’ token
  113 |             KD_TREE<MapPoint>::Ptr new_map = KD_TREE<MapPoint>::Ptr (new KD_TREE<MapPoint>(0.3, 0.6, 0.01));
      |                             ^
/home/src/fast_LIMO/include/fast_limo/Modules/Mapper.cpp:113:32: error: ‘::Ptr’ has not been declared
  113 |             KD_TREE<MapPoint>::Ptr new_map = KD_TREE<MapPoint>::Ptr (new KD_TREE<MapPoint>(0.3, 0.6, 0.01));
      |                                ^~~
/home/src/fast_LIMO/include/fast_limo/Modules/Mapper.cpp:123:13: error: ‘new_map’ was not declared in this scope; did you mean ‘get_map’?
  123 |             new_map->Build(map_vec);
      |             ^~~~~~~
      |             get_map
```

**Comment by fetty31** [comment]
Hi @mini-1235,

Thank you so much for your feedback. I just fixed this issue. Try it when you can and do not hesitate to reach out if you find more problems!

**Comment by mini-1235** [comment]
Hi, the error I pasted above is just part of my compilation error, after using the latest commit, I am still unable to compile. I fixed this in #18, can you take a look?
